apiVersion: apps/v1
kind: Deployment
metadata:
  name: chuck-shiny
  labels:
    app: chuck-shiny
spec:
  selector:
    matchLabels:
      app: shiny
      tier: frontend
  template:
    metadata:
      labels:
        app: shiny
        tier: frontend
    spec:
      containers:
        - name: chuck
          image: colinfay/chuck:0.0.1
          env:
            - name: MONGOPORT
              valueFrom:
                configMapKeyRef: 
                  name: shiny-cm
                  key: mongoport
            - name: MONGOURL
              value: chuck-mongo
            - name: MONGODB
              valueFrom:
                secretKeyRef: 
                  name: shiny-secret
                  key: db
            - name: MONGOCOLLECTION
              valueFrom:
                secretKeyRef: 
                  name: shiny-secret
                  key: collection
            - name: PORT
              valueFrom:
                configMapKeyRef: 
                  name: shiny-cm
                  key: shinyport
          ports:
            - containerPort: 3838
